version: '3.8'

services:
  db:
    image: postgres:16
    container_name: chess_db
    restart: always
    environment:
      POSTGRES_USER: chessuser
      POSTGRES_PASSWORD: chesspass
      POSTGRES_DB: chess_master
    ports:
      - "5432:5432"   # hostPort:containerPort
    volumes:
      - chess_data:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: chess_redis
    restart: always
    command: ["redis-server", "--requirepass", "redis-pass"]
    environment:
      REDIS_PASSWORD: redis-pass
    ports:
      - "6378:6379"
  

volumes:
  chess_data:
